### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Thermelgy-Repo** [rykovv/spiffs_circular_queue#1]
Thanq for your great library, Can u plz include documentation and an example code, So that for us that will be helpful

**Comment by rykovv** [comment]
Yeah, I have generated the documentation, plz see the repo description and added the basic workflow in the examples folder

**Comment by rykovv** [comment]
> Thanq for your great library, Can u plz include documentation and an example code, So that for us that will be helpful

Yeah, I have generated the documentation, plz see [the link](https://rykovv.github.io/spiffs_circular_queue/) in repo description and added the basic workflow in the examples folder
