### ISSUE TITLE
Define file max size dynamically as part of circular_queue_t

### ISSUE THREAD

**Issue by aokrasavin** [rykovv/spiffs_circular_queue#3]
May I suggest that instead of defining file max size as a global fixed value (SPIFFS_CIRCULAR_QUEUE_FILE_MAX_SIZE), it should be defined as part of  circular_queue_t, so could be set individually and dynamically for different queues. I have a requirement for queues with different sizes (completely different types of data), also where the file size is controlled dynamically based on availability of SPIFFS space (and reajusted regularly based on situation)

**Comment by rykovv** [comment]
@aokrasavin Thank you for the good suggestions! The user-defined queue size feature was included in the upcoming release. I will include the dynamically settable and expandable based on available space size too.

**Comment by rykovv** [comment]
Introduced in the Release 1.2
