### ISSUE TITLE
Add library.properties file

### ISSUE THREAD

**Issue by aokrasavin** [rykovv/spiffs_circular_queue#4]
Add library.properties file containing essentially the same information as library.json, but for those unenlightened tools which do not know how to deal with JSON (Microsoft - polite nudge in your direction). Simplifies having the library recognised :-)

[library.properties.zip](https://github.com/rykovv/spiffs_circular_queue/files/9219306/library.properties.zip)

**Comment by rykovv** [comment]
@aokrasavin For sure! It'll be in the next release too. Thanks

**Comment by rykovv** [comment]
Added in the Release 1.2
